---
- name: Snapshot ABI cluster
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Store clusterDir in a fact
    ansible.builtin.set_fact: clusterDir="{{ clusterBaseDir|default('../clusters') }}/{{ name }}.{{ baseDomain }}"

  - name: Create snapshot of virtual machines
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter.hostname }}"
      username: "{{ vcenter.username }}"
      password: "{{ vcenter.password }}"
      datacenter: "{{ vcenter.datacenter }}"
      validate_certs: no
      name: "node{{ '%02d'|format(loop) }}.{{ name }}.{{ baseDomain }}"
      folder: "/{{ vcenter.datacenter }}/vm/"
      state: present
      snapshot_name: "{{ snapshot_name | default('snap1') }}"
      quiesce: "{{ quiesce|  default('false') }}"
    loop: "{{ range(controlPlaneReplicas|int + computeReplicas|int) }}"
    loop_control:
      loop_var: loop
    ignore_errors: true
