---
- name: Create required files for ABI deployment
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Store clusterDir in a fact
    ansible.builtin.set_fact: clusterDir="{{ clusterBaseDir|default('../clusters') }}/{{ name }}.{{ baseDomain }}"

  - name: Remove destination directory (if any)
    ansible.builtin.shell: "rm -vfr {{ clusterDir }}"

  - name: Create destination directory
    ansible.builtin.file:
      path: "{{ clusterDir }}"
      state: directory

  - name: Generate ABI input files
    ansible.builtin.template:
      src: "../templates/{{ item }}.j2"
      dest: "{{ clusterDir }}/{{ item }}"
    vars:
      control_plane_interfaces: "{{ vms.controlPlaneData.interfaces }}"
      compute_interfaces: "{{ vms.computeData.interfaces }}"
    with_items:
    - install-config.yaml
    - agent-config.yaml

  - name: Generate ABI input files (backups)
    ansible.builtin.template:
      src: "../templates/{{ item }}.j2"
      dest: "{{ clusterDir }}/{{ item }}.orig"
    vars:
      control_plane_interfaces: "{{ vms.controlPlaneData.interfaces }}"
      compute_interfaces: "{{ vms.computeData.interfaces }}"
    with_items:
    - install-config.yaml
    - agent-config.yaml
