---
- name: Monitor installation process
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Store clusterDir in a fact
    ansible.builtin.set_fact: clusterDir="{{ clusterBaseDir|default('../clusters') }}/{{ name }}.{{ baseDomain }}"

  - name: Waiting for bootstrap to complete
    ansible.builtin.shell: "openshift-install --dir {{ clusterDir }} agent wait-for bootstrap-complete"

  - name: Waiting for installation to complete
    ansible.builtin.shell: "openshift-install --dir {{ clusterDir }} agent wait-for install-complete"
